modLoader="javafml"
loaderVersion="[42,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/AbdElAziz333/Canary/issues"
[[mods]]
modId = "canary"
version = "${version}"
displayName = "Canary"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/canary"
logoFile = "logo.png"
credits = "AbdElAziz, JellySquid, 2No2Name"
authors = "AbdElAziz"
displayTest = "MATCH_VERSION"

description = '''
Canary is a free and open-source optimization mod for Minecraft which makes a wide range of performance improvements to the game.
'''

[[dependencies.canary]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.canary]]
    modId="minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
    side="BOTH"