modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

issueTrackerURL = "https://github.com/AbdElAziz333/Canary/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://github.com/AbdElAziz333/Canary/raw/mc1.19.2/dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/canary"
logoFile = "logo.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"