modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/AbdElAziz333/Canary/issues"
[[mods]]
modId = "canary"
version = "${file.jarVersion}"
displayName = "Canary"
updateJSONURL = "https://github.com/AbdElAziz333/Canary/raw/mc1.19.2/dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/canary"
logoFile = "logo.png"
credits = "AbdElAziz, JellySquid, 2No2Name"
authors = "AbdElAziz"

description = '''
Canary is a free and open-source optimization mod for Minecraft which makes a wide range of performance improvements to the game.
'''

[[dependencies.canary]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.canary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"