#General configuration settings
[general]
#Set this to true to cache resource listings in resource and data packs
cachePackAccess = true
#Set this to true to index vanilla resource and data packs on thread
indexVanillaPackCachesOnThread = false
#Set this to true to index mod resource and data packs on thread
indexModPackCachesOnThread = false

